### ISSUE TITLE
ImportError: cannot import name 'Iterable' from 'collections' 

### ISSUE THREAD

**Issue by AMzaheri** [cgre-aachen/gempy#705]
Hello,
I’ve installed gempy using pip on Ubuntu22. I was wondering if you could advise me on how to solve the following error which happens when I import it :

Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "~ /.local/lib/python3.10/site-packages/gempy/__init__.py", line 25, in <module>
    from gempy.gempy_api import *
  File "~ /.local/lib/python3.10/site-packages/gempy/gempy_api.py", line 17, in <module>
    from gempy.core.model import Project
  File "~ /.local/lib/python3.10/site-packages/gempy/core/model.py", line 17, in <module>
    from gempy.core.interpolator import InterpolatorModel, InterpolatorGravity
  File "~ /.local/lib/python3.10/site-packages/gempy/core/interpolator.py", line 1, in <module>
    from collections import Iterable
ImportError: cannot import name 'Iterable' from 'collections' (/usr/lib/python3.10/collections/__init__.py).

I’ve installed gempy using conda as well. But the same import error happens. 
I'd be grateful, if you could help.

**Comment by Japhiolite** [comment]
That's been fixed and merged in PR #686 .
It hasn't made its way to pip yet, but you could use the github master as working with gempy.

**Comment by AMzaheri** [comment]
Thank you for your response. I've used the github master, but a new error happened:
AttributeError: module 'numpy.distutils.__config__' has no attribute 'blas_opt_info'.

Thank you for your help.

**Comment by Japhiolite** [comment]
what is your numpy version? Can you provide an output of your environment you're using Gempy in?

**Comment by AMzaheri** [comment]
I'm running GemPy on Ubuntu 2022 installed on VirtualBox, and I'm using numpy 1.23.0.
Thank you.

**Comment by Japhiolite** [comment]
numpy 1.23.0 is a very recent development (1 week old), so there might be changes, which affect gempy.
To ensure properly running of gempy, better ensure to run numpy 1.22.x (e.g. I have 1.22.2 running).

**Comment by Japhiolite** [comment]
That's a linux specific problem, not caused by gempy. 
On the new Ubuntu 22, wayland is the default. Might maybe help to set this back to xorg 
https://stackoverflow.com/questions/69828508/warning-ignoring-xdg-session-type-wayland-on-gnome-use-qt-qpa-platform-wayland

**Comment by Japhiolite** [comment]
Hi @georgebisbas 

`Iterable` was removed from `collections` with Python 3.10. So that's where the error is coming from. I'll re-check the next days, how vital that import is...I remember, that it was kinda obsolete.
I've GemPy working with Py 3.8, 3.9. So in the meantime, any env with those versions should work. 
Anyhow, with 3.10 we'll solve this in the near future.

**Comment by AMzaheri** [comment]
Hello,

I managed to install GemPy with python 3.8 successfully. Thank you.
